InventoryHubUI/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using InventoryHubUI.DTO;
using InventoryHubUI.Services;
using InventoryHubUI.Models;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Http;
using System.Text;
using System.Net.Http.Headers;
using InventoryHubUI.ModelViews;

namespace InventoryHubUI.Controllers
{

    public class CategoryController : Controller
    {
        private readonly HttpClient _httpClient;

        public CategoryController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        

        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10)
        {
            var url = $"{API_EndPoint.Category_ENDPoint}?pageNumber={pageNumber}&pageSize={pageSize}";

            var response = await _httpClient.GetAsync(url);
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var categories = JsonConvert.DeserializeObject<List<Category>>(content);

                string apiGetCountCategories = $"{API_EndPoint.Category_ENDPoint}GetCountCategories";
                var responseGetCountCategories = await _httpClient.GetAsync(apiGetCountCategories);
                var contentGetCountCategories = await responseGetCountCategories.Content.ReadAsStringAsync();

                ViewData["CurrentPage"] = pageNumber;
                ViewData["PageSize"] = pageSize;
                ViewData["TotalItems"] = Convert.ToInt32(contentGetCountCategories);
                return View(categories);
            }
            return View();
        }

        public async Task<IActionResult> GetCategoriesAsync()
        {
            var response = await _httpClient.GetAsync(API_EndPoint.CategoryENDPoint);

            // التحقق من النتيجة
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var Categories = JsonConvert.DeserializeObject<List<Category>>(content);

                // الطلب تم بنجاح
                return Json(Categories);
            }
            else
            {
                return Json(new List<Category>());
            }
        }


        public async Task<IActionResult> GetCategory(int id)
        {
            string endPoint = $"{API_EndPoint.Category_ENDPoint}getcategorybyid?id={id}";
            var response = await _httpClient.GetAsync(endPoint);

            // التحقق من النتيجة
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var category = JsonConvert.DeserializeObject<Category>(content);

                // الطلب تم بنجاح
                return Json(new { category });
            }
            else
            {
                return Json("");
            }
        }

        [HttpPost("CreateCategory")]
        public async Task<IActionResult> CreateCategory([FromForm] Category category)
        {
            var url = $"{API_EndPoint.Category_ENDPoint}CreateCategory";
            // إعداد البيانات التي سيتم إرسالها عبر POST
            var form = new MultipartFormDataContent();
            form.Add(new StringContent(category.Name), "Name");
            form.Add(new StringContent(category.Code), "Code");

            var response = await _httpClient.PostAsync(url, form);

            if (response.IsSuccessStatusCode && (int)response.StatusCode == StatusCodes.Status200OK)
            {
                var content = await response.Content.ReadAsStringAsync();
                var categoryCreated = JsonConvert.DeserializeObject<Category>(content);
                return Json(new { message = "Create Category Successfully", success = "true", categoryCreated });
            }
            else
            {
                var errorMessage = await response.Content.ReadAsStringAsync();
                return Json(new { message = errorMessage, success = "false" });
            }

        }

        [HttpPost]
        public async Task<IActionResult> EditCategory([FromForm] Category category)
        {
                var url = $"{API_EndPoint.Category_ENDPoint}";
                // إعداد البيانات التي سيتم إرسالها عبر POST
                var form = new MultipartFormDataContent();
                form.Add(new StringContent(category.CategoryId.ToString()), "CategoryId");
                form.Add(new StringContent(category.Name), "Name");
                form.Add(new StringContent(category.Code), "Code");

                var response = await _httpClient.PutAsync(url, form);
                
                if (response.IsSuccessStatusCode && (int)response.StatusCode == StatusCodes.Status200OK)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    var categoryUpdated = JsonConvert.DeserializeObject<Category>(content);
                    return Json(new { message = "Category Updated Successfully", success = "true" ,categoryUpdated});
                }
                else
                {
                    var errorMessage = await response.Content.ReadAsStringAsync();
                    return Json(new { message = errorMessage, success = "false" });
                }
            
        }


        [HttpDelete]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            var response = await _httpClient.DeleteAsync($"{API_EndPoint.APIURI}api/Category?id={id}");
            response.EnsureSuccessStatusCode();
            if (response.IsSuccessStatusCode && (int)response.StatusCode == StatusCodes.Status204NoContent)
            {
                return Json(new { message="Categor Deleted Succesfully.",success="true"});
            }
            return Json(new { message="please try again.",success="false"});
        }
    }

}

InventoryHubUI/Controllers/CustomerController.cs
using InventoryHubUI.Models;
using InventoryHubUI.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace InventoryHubUI.Controllers
{
    public class CustomerController : Controller
    {
        private readonly HttpClient _httpClient;
        public CustomerController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }
        public async Task<IActionResult> Index()
        {
            var resonse = await _httpClient.GetAsync(API_EndPoint.GetCustomerENDPoint);
            if(resonse.IsSuccessStatusCode)
            {
                string content = await resonse.Content.ReadAsStringAsync();
                var Customers = JsonConvert.DeserializeObject<List<CustomerViewModel>>(content);
                return View(Customers);
            }
            return View(new CustomerViewModel());
        }

        [HttpPost("CreateCustomer")]
        public async Task<IActionResult> CreateCustomer(CreateCustomerViewModel customerView)
        {
            var formData = new MultipartFormDataContent();
            formData.Add(new StringContent(customerView.FirstName), "FirstName");
            formData.Add(new StringContent(customerView.LastName), "LastName");
            formData.Add(new StringContent(customerView.Address), "Address");
            formData.Add(new StringContent(customerView.Email), "Email");
            formData.Add(new StringContent(customerView.PhoneNumber), "PhoneNumber");

            if (customerView.CustomerImage != null)
            {
                var fileStream = customerView.CustomerImage.OpenReadStream();
                var fileContent = new StreamContent(fileStream);

                // إضافة رأس الملف لمزيد من المعلومات مثل نوع المحتوى واسم الملف
                fileContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(customerView.CustomerImage.ContentType);

                // إضافة الملف إلى الفورم
                formData.Add(fileContent, "CustomerImage", customerView.CustomerImage.FileName);
            }

            string url = $"{API_EndPoint.CreateCustomerENDPoint}";

            var response = await _httpClient.PostAsync(url,formData);

            if(response.IsSuccessStatusCode )
            {
                var Content = await response.Content.ReadAsStringAsync();

                if(response.StatusCode == System.Net.HttpStatusCode.Created)
                {
                    var jsonConvert = JsonConvert.DeserializeObject<GetCustomerViewModel>(Content);
                    return Json(new { Customer = jsonConvert,success="true" });

                }


            }
            if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
            {
                var msgError = await response.Content.ReadAsStringAsync();
                return Json(new { message = msgError, success = "false" });
            }
            return Json(new {message="Try Again", success="false" });
        }

        

        [HttpGet("GetCustomerById")]
        public async Task<IActionResult> GetCustomerById(int CustomerId)
        {
            if (CustomerId <= 0)
                return Json(new { message="Invalid Customer Id",success="false"});

            string url = $"{API_EndPoint.GetCustomerByIdENDPoint}/{CustomerId}";

            var response = await _httpClient.GetAsync(url);

            if (response.IsSuccessStatusCode)
            {
                var Content = await response.Content.ReadAsStringAsync();
                var jsonConvert = JsonConvert.DeserializeObject<GetCustomerViewModel>(Content);
                return Json(new { Customer = jsonConvert, success = "true" });
            }

            return Json(new { message="Invalid Customer Id",success="false"});
        }

        [HttpPost("EditCustomer")]
        public async Task<IActionResult> EditCustomer(EditCustomerViewModel customerViewModel)
        {
            var formData = new MultipartFormDataContent();
            formData.Add(new StringContent(customerViewModel.CustomerId.ToString()), "CustomerId");
            formData.Add(new StringContent(customerViewModel.FirstName), "FirstName");
            formData.Add(new StringContent(customerViewModel.LastName), "LastName");
            formData.Add(new StringContent(customerViewModel.Address), "Address");
            formData.Add(new StringContent(customerViewModel.Email), "Email");
            formData.Add(new StringContent(customerViewModel.PhoneNumber), "PhoneNumber");
            formData.Add(new StringContent(customerViewModel.CustomerImageUrl), "CustomerImageUrl");

            if (customerViewModel.CustomerImage != null)
            {
                var fileStream = customerViewModel.CustomerImage.OpenReadStream();
                var fileContent = new StreamContent(fileStream);

                // إضافة رأس الملف لمزيد من المعلومات مثل نوع المحتوى واسم الملف
                fileContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(customerViewModel.CustomerImage.ContentType);

                // إضافة الملف إلى الفورم
                formData.Add(fileContent, "CustomerImage", customerViewModel.CustomerImage.FileName);
            }

            string url = $"{API_EndPoint.EditCustomerENDPoint}";


            var response = await _httpClient.PatchAsync(url,formData);

            if (response.IsSuccessStatusCode)
            {
                var Content = await response.Content.ReadAsStringAsync();
                var jsonConvert = JsonConvert.DeserializeObject<GetCustomerViewModel>(Content);
                return Json(new { Customer = jsonConvert, success = "true" });
            }

            return Json(new { message = "Try Again", success = "false" });
        }

        [HttpPost("ChangeStatus")]
        public async Task<IActionResult> ChangeStatus(int CustomerId)
        {
            if (CustomerId <= 0)
                return Json(new { message = "Invalid Customer Id", success = "false" });

            string url = $"{API_EndPoint.ChangeStatusENDPoint}/?CustomerId={CustomerId}";

            var response = await _httpClient.PostAsync(url,null);

            if (response.IsSuccessStatusCode)
            {
                var Content = await response.Content.ReadAsStringAsync();
                var isActive = JsonConvert.DeserializeObject<string>(Content);
                return Json(new { isActive, success = "true" });
            }

            return Json(new { message = "Invalid Customer Id", success = "false" });
        }

        [HttpPost("DeleteCustomer")]
        public async Task<IActionResult> DeleteCustomer(int CustomerId)
        {
            if (CustomerId <= 0)
                return Json(new { message = "Invalid Customer Id", success = "false" });

            string url = $"{API_EndPoint.DeleteCustomerENDPoint}/?CustomerId={CustomerId}";

            var response = await _httpClient.DeleteAsync(url);

            if (response.IsSuccessStatusCode)
            {
                return Json(new { message = "Customer Deleted Successfuly", success = "true" });
            }

            return Json(new { message = "Invalid Customer Id", success = "false" });
        }
    }


}

InventoryHubUI/Views/Shared/_CustomerPartial.cshtml
<style>
    @@media (min-width: 576px) {
        .modal-dialog {
            max-width: 800px !important;
        }
    }

    input[type="text"] {
        border: 1px solid #e2e2e2;
    }

    .div-Image-Area {
        text-align: center;
        position: relative;
        display: flex;
        justify-content: center;
        margin: 10px 0;
    }

    .img-area {
        width: 80px;
        height: 80px;
        border-radius: 50%;
        overflow: hidden;
    }

        .img-area img {
            width: 100%;
            height: 100%;
        }

    .layout-circle {
        border-radius: 50%;
        padding: 9px;
        border: 1px solid #bababa;
        background: #bababa;
    }
</style>
<div class="modal fade" id="CustomerModal" tabindex="-1" role="dialog" aria-labelledby="CustomerModalLabel" aria-hidden="true" style="top:10%;">
    <input id="key-CustomerId" value="" hidden />
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="CustomerModalLabel">
                </h5>
            </div>
            <div class="modal-body">
                <form id="CustomerForm">
                    <div class="row">
                        <div class="col-md-12 div-Image-Area">
                            <div class="icon-upload-image">
                                <input type="file" style="display:none" id="file-upload-image" />
                                <span id="upload-image" style="position: absolute; bottom: 0; left: 53%; font-size: 18px; padding: 4px 11px; background: #f3f1f1; border-radius: 50%; color: #817a7a;cursor:pointer; ">
                                    <i class="bi bi-image-fill"></i>
                                </span>
                            </div>
                            <div class="layout-circle">

                                <div class="img-area">
                                    <img id="customer-image" src="~/Images/Dark Default Pfp.jpeg" alt="Customer Photo" />
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="firstname" class="col-form-label">
                                    First Name <span style="color:red;">*</span>
                                </label>
                                <input type="text" class="form-control" id="FirstName-modal" name="firstname" value="" placeholder="Enter First Name">

                            </div>

                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="lastname" class="col-form-label">
                                    Last Name <span style="color:red;">*</span>
                                </label>
                                <input type="text" class="form-control" id="LastName-modal" name="lastname" value="" placeholder="Enter Last Name">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="email" class="col-form-label">
                                    Email <span style="color:red;">*</span>
                                </label>
                                <input type="email" class="form-control" id="Email-modal" name="email" value="" placeholder="Enter Email">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="phone" class="col-form-label">
                                    Phone <span style="color:red;">*</span>
                                </label>
                                <input type="text" class="form-control" id="Phone-modal" name="phone" value="" placeholder="Enter Phone">
                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                <label for="address" class="col-form-label">
                                    Address <span style="color:red;">*</span>
                                </label>
                                <input type="text" class="form-control" id="Address-modal" name="address" value="" placeholder="Enter Address">
                            </div>
                        </div>

                    </div>
                    <!-- Add more fields as needed -->
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn background-design" hidden id="edit-action-modal">Edit</button>
                <button type="button" class="btn background-design" hidden id="create-action-modal">Create</button>
                <button type="button" class="btn btn-danger" id="del-action-modal" hidden>OK</button>
            </div>
        </div>
    </div>
</div>

InventoryHubUI/Views/Shared/_EditCategoryModal.cshtml
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true" style="top:20%;">
    <input id="key" value="" hidden/>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">

                </h5>
            </div>
            <div class="modal-body">
                <form id="editCategoryForm">
                    <div class="form-group">
                        <label for="name" class="col-form-label">
                            Name:
                        </label>
                        <input type="text" class="form-control" id="name-modal" name="name" value="">
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-form-label">
                            Code:
                        </label>
                        <input type="text" class="form-control" id="code-modal" name="code" value="">
                    </div>
                    <!-- Add more fields as needed -->
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn background-design" hidden id="edit-action-modal">Edit</button>
                <button type="button" class="btn background-design" hidden id="create-action-modal">Create</button>
                <button type="button" class="btn btn-danger"  id="del-action-modal" hidden>OK</button>
            </div>
        </div>
    </div>
</div>

InventoryHubUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using System.Text

@{ 
    var refreshTokenBytes = Context.Session.Get("RefreshToken");
    var refreshToken = refreshTokenBytes != null ? Encoding.UTF8.GetString(refreshTokenBytes) : null;
    var firstName = User.Claims.FirstOrDefault(c => c.Type == "FirstName")?.Value;
    var lastName = User.Claims.FirstOrDefault(c => c.Type == "LastName")?.Value;
 }
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZULU</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/lib/toastr.js/toastr.min.css" />
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
    <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.7/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <div class="wrapper">
        @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(Context.Session.GetString("RefreshToken")))
        {
            <nav id="sidebar" class="bg-light border-right">
                <div class="sidebar-header">
                    <h3>
                        ZULU
                        <img src="~/svgviewer-white.png" alt="logo" style="width: 100px; height: 100px;" />
                    </h3>
                    <p style="font-size:14px">Inventory Hub</p>
                </div>

                <ul class="list-unstyled components">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                    </li>
                </ul>
            </nav>}

        <!-- Main Content -->
    <div id="content">
        @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(Context.Session.GetString("RefreshToken")))
        {
            <nav class="navbar-header navbar navbar-expand-lg navbar-light bg-white border-bottom header-nav-info">
                <div class="dropdown header-item" style="height: 70px; display: flex; align-items: center;">
                    <button type="button" class="btn" id="page-header-user-dropdown">
                        <span class="d-flex align-items-center">
                            <img alt="Header Avater" src="~/Images/Dark Default Pfp.jpeg" style="width:30px;height:30px;border-radius:50%;margin:0 5px;" />
                            <span class="text-start ms-xl-2">
                                @firstName  @lastName 
                                <i class="bi bi-chevron-down"></i>
                            </span>
                        </span>
                    </button>
                </div>
                <div id="profile_menu" class="profile_menu" hidden>
                    <ul>
                        <li class="link">
                            <span>
                                <i class="bi bi-person-fill"></i>
                                Profile
                            </span>
                        </li>
                        <li class="link">
                            <span>
                                <i class="bi bi-gear"></i>
                                Settings
                            </span>
                        </li>
                        <li style="width: 100%; border: 1px solid #f1e8e8bd; margin: 5px 0;"></li>
                        <li class="link">
                            <span>
                                <i class="bi bi-power"></i>
                                <a href="javascript:void(0);" onclick="logout()" style="color: red; text-decoration: none;">Logout</a>

                            </span>
                        </li>
                    </ul>
                </div>
            </nav>
        }
        @{ 
            var paddingStyle = "padding: 0 15px;";
            if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(Context.Session.GetString("RefreshToken")))
            {
                paddingStyle = "padding: 100px 15px 0;";
            } 
        }
        <main role="main" class="pb-3" style="@paddingStyle">
        
            @RenderBody()
        </main>
    </div>
    

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2024 - ZULU Inventory Hub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // LOGOUT
        function logout() {
            $.ajax({
                url: '@Url.Action("Logout", "Account")',
                type: 'POST',
                contentType: 'application/json',
                success: function (data) {
                    console.log('Logout successful:', data);
                    window.location.href = '@Url.Action("Login", "Account")';
                    sessionStorage.removeItem('JWTToken');
                    sessionStorage.removeItem('RefreshToken');
                },
                error: function (xhr, status, error) {

                    console.error('Error during logout:', error);
                }
            });
        }
    </script>
    @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(Context.Session.GetString("RefreshToken")))
    {
        <script>
              $(document).ready(function () {
                    const checkTokenInterval = 5 * 60 * 1000;


                    function refreshJwtToken() {

                        $.ajax({
                            url: '@Url.Action("RefreshToken","Account")',
                            type: 'POST',
                            contentType: 'application/json',

                            success: function (data) {
                                
                                console.log(data)
                                if (data) {
                                    sessionStorage.setItem('JWTToken', data.newToken);
                                    sessionStorage.setItem('RefreshToken', data.newRefreshToken);
                                } else {
                                    console.error('Failed to refresh token');
                                }
                            },
                            error: function (xhr, status, error) {
                                console.error('Error refreshing token');
                            }
                        });
                    }

                    setInterval(refreshJwtToken, checkTokenInterval);
                });
        </script>
    }


 



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/toastrOptions.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/spin.js@2.3.2/spin.min.js"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>