InventoryHubUI/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace InventoryHubUI.Models
{
    public class Product
    {
        [Key]
        public int ProductId { get; set; }

        [Required(ErrorMessage = "Product Name is required.")]
        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(500)]
        public string Description { get; set; }
        public string Code { get; set; }
       
        public decimal? StockQuantity { get; set; }

        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Price must be a positive value.")]
        public decimal Price { get; set; }
        public string ImagePath { get; set; }
        [Required]
        public int CategoryId { get; set; }
        [JsonIgnore]
        public Category Category { get; set; }
      
        public int? StoreId { get; set; }
        [JsonIgnore]
        public Store Store { get; set; }
    }
    

}

InventoryHubUI/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using InventoryHubUI.DTO;
using InventoryHubUI.Services;
using InventoryHubUI.Models;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Http;
using System.Text;
using System.Net.Http.Headers;
using InventoryHubUI.Services.HelperMethods;
using Microsoft.AspNetCore.Mvc.Rendering;
using InventoryHubUI.ModelViews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using InventoryHubUI.Services.TokenHeader;

namespace InventoryHubUI.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly ICategoryService _categoryService;
        private readonly IStoreService _storeService;
        private readonly IHeaderBearerToken _headerBearerToken;


        public ProductsController(HttpClient httpClient,ICategoryService categoryService, IStoreService storeService, IHeaderBearerToken headerBearerToken)
        {
            _httpClient = httpClient;
            _categoryService = categoryService;
            _storeService = storeService;
            _headerBearerToken = headerBearerToken;
        }
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10)
        {
            var url = $"{API_EndPoint.ProductENDPoint}?pageNumber={pageNumber}&pageSize={pageSize}";

            var tokenHeader = await _headerBearerToken.HeaderTokenRequest();
            if(string.IsNullOrEmpty(tokenHeader))
                return RedirectToAction("UnauthorizedAccess", "Account");

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenHeader);
            var response = await _httpClient.GetAsync(url);

            if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                // إعادة توجيه إلى صفحة Unauthorized
                return RedirectToAction("UnauthorizedAccess", "Account");
            }

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var pagedResponse = JsonConvert.DeserializeObject<PagedResponse<ProductViewModel>>(content);
                var products = pagedResponse.Items.ToList();
                var TotalItems = pagedResponse.TotalItems;
                ViewData["CurrentPage"] = pageNumber;
                ViewData["PageSize"] = pageSize;
                ViewData["TotalItems"] = TotalItems;
                return View(products);
            }

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> CreateProduct()
        {
            ViewData["Title"] = "Create Product";
            var Categories = await _categoryService.GetCategoriesAsync();
            // تحويل التصنيفات إلى قائمة SelectListItem
            ViewBag.CategoryList = Categories.Select(c => new SelectListItem
            {
                Value = c.CategoryId.ToString(),
                Text = c.Name
            }).ToList(); 

            var Stores = await _storeService.GetStoresAsync();
            ViewBag.StoreList = Stores.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.StoreName
            }).ToList();
            return View(new Product()); 
        }
      

        [HttpPost]
        public async Task<JsonResult> CreateProduct(Product product, IFormFile ImagePath)
        {
            using (var client = new HttpClient())
            {
                // تعيين الـ URL للـ API الخاص بك

                // إنشاء MultipartFormDataContent لإرسال البيانات مع الملفات
                using (var form = new MultipartFormDataContent())
                {
                    // إضافة بيانات المنتج
                    form.Add(new StringContent(product.Name), "Product.Name");
                    form.Add(new StringContent(product.Code), "Product.Code");
                    form.Add(new StringContent(product.Description??""), "Product.Description");
                    form.Add(new StringContent(product.Price.ToString()), "Product.Price");
                    form.Add(new StringContent(product.StockQuantity?.ToString()), "Product.StockQuantity");
                    form.Add(new StringContent(product.CategoryId.ToString()), "Product.CategoryId");

                    // إضافة الصورة إلى الفورم إذا كانت موجودة
                    if (ImagePath != null && ImagePath.Length > 0)
                    {
                        var streamContent = new StreamContent(ImagePath.OpenReadStream());
                        form.Add(streamContent, "ImagePath", ImagePath.FileName);
                    }

                    // إرسال الطلب إلى الـ API
                    var response = await client.PostAsync(API_EndPoint.CreateProductENDPoint, form);

                    // التحقق من النتيجة
                    if (response.IsSuccessStatusCode)
                    {
                        // الطلب تم بنجاح
                        return Json(new { Message= "Product added successfully!", Success="true" });
                    }
                    else
                    {
                        // خطأ في الطلب
                        ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                        return Json(new { Message= "Failed to add the product.", Success="false" });
                    }
                }
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditProduct(int id)
        {
            var tokenHeader = await _headerBearerToken.HeaderTokenRequest();
            if (string.IsNullOrEmpty(tokenHeader))
                return RedirectToAction("UnauthorizedAccess", "Account");

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenHeader);
            string url = API_EndPoint.EditProductEndPoint(id);
            var response = await _httpClient.GetAsync(url);


            if (response.IsSuccessStatusCode)
            {
                // التعامل مع استجابة ناجحة
                var responseContent = await response.Content.ReadAsStringAsync();
                Product product = JsonConvert.DeserializeObject<Product>(responseContent);
                var Categories = await _categoryService.GetCategoriesAsync();
                var Stocks = await _storeService.GetStoresAsync();

                ViewBag.CategoryList = new SelectList(Categories, "CategoryId", "Name");
                ViewBag.StocksList = new SelectList(Stocks, "StockId", "Name");
                // معالجة المحتوى إذا لزم الأمر
                return View(product);
            }
            else
            {
                return View(new Product());
                // التعامل مع الاستجابة الفاشلة
            }
        }
        
        [HttpPost]
        public async Task<JsonResult> EditProduct([FromForm] ProductViewModel productViewModel)
        {
            var url = API_EndPoint.EditProductAPIENDPoint_Post(productViewModel.ProductId);
            // إعداد البيانات التي سيتم إرسالها عبر POST
            var form = new MultipartFormDataContent();
            form.Add(new StringContent(productViewModel.ProductId.ToString()), "ProductId");
            form.Add(new StringContent(productViewModel.Name), "Name");
            form.Add(new StringContent(productViewModel.Code), "Code");
            form.Add(new StringContent(productViewModel.Price.ToString()), "Price");
            form.Add(new StringContent(productViewModel.StockQuantity.ToString()), "StockQuantity");
            form.Add(new StringContent(productViewModel.Description), "Description");
            form.Add(new StringContent(productViewModel.ImagePath), "ImagePath");
            form.Add(new StringContent(productViewModel.StockId.ToString()), "StockId");
            form.Add(new StringContent(productViewModel.CategoryId.ToString()), "CategoryId");

            var tokenHeader = await _headerBearerToken.HeaderTokenRequest();
            if (string.IsNullOrEmpty(tokenHeader))
                return Json(new { message = "UnauthorizedAccess", success = "false" });

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenHeader);

            var response = await _httpClient.PutAsync(url, form);

            if (response.IsSuccessStatusCode && (int)response.StatusCode == StatusCodes.Status204NoContent)
            {
                return Json(new { message = "Product Updated Successfully", success = "true" });
            }
            else
            {
                var errorMessage = await response.Content.ReadAsStringAsync();
                return Json(new { message = errorMessage, success = "false" });
            }
        }

        [HttpPost]
        public async Task<IActionResult> ChangeProductImage([FromForm] ProductImage productImage)
        {
            if (productImage.ImagePath == null || productImage.ImagePath.Length == 0)
                return Json(new { message = "No file uploaded.", success = "false" });

            if (string.IsNullOrEmpty(productImage.Id))
                return Json(new { message = "refresh page and try again.", success = "false" });

            int productId;
            if (!int.TryParse(productImage.Id, out productId))
                return Json(new { message = "Invalid ProductId.", success = "false" });


            try
            {

                productImage.ProductId = productId;
                string url = API_EndPoint.ChangeProductImageEndpoint(productImage);
                // إعداد البيانات التي سيتم إرسالها عبر POST
                var form = new MultipartFormDataContent();

InventoryHubUI/Views/Products/CreateProduct.cshtml
@model InventoryHubUI.Models.Product

<link href="~/css/CreateProduct.css" rel="stylesheet" />
<link href="~/css/SelectDesign.css" rel="stylesheet" />


<div style="display:flex;align-items:center;padding:10px 15px;">
    <h2>@ViewData["Title"]</h2>
</div>
<form method="post" enctype="multipart/form-data" style="padding:0 17px;">
    <section class="row" style="padding:15px;">
        <div class="col-md-8" style="background-color:#ffffff;height:80%;padding:16px 19px;border-radius:10px;">
            <div class="form-group">
                <label asp-for="Name">Prdouct Name <span class="span-wraning">*</span></label>
                <input asp-for="Name" placeholder="Enter Product Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Code">Code <span class="span-wraning">*</span></label>
                <input asp-for="Code" placeholder="Product Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description">Description</label>
                <textarea asp-for="Description" placeholder="Description" class="form-control" style="height:200px;width:100%;resize:none;"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <h3>Stock & Pricing</h3>
            <div style="display:flex; justify-content:flex-start;">

                <div class="form-group" style="flex:1">
                    <label asp-for="Price">Price <span class="span-wraning">*</span></label>
                    <input asp-for="Price" placeholder="Enter Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="form-group" style="flex:1">
                    <label asp-for="StockQuantity">StockQuantity <span class="span-wraning">*</span></label>
                    <input asp-for="StockQuantity" placeholder="Enter Stock Quantity" class="form-control" />
                    <span asp-validation-for="StockQuantity" class="text-danger"></span>
                </div>
            </div>
            <div style="display:flex;">
                <div class="form-group" style="flex:1;margin-right:4px;">
                    <label asp-for="CategoryId">Category <span class="span-wraning">*</span></label>
                    <select asp-for="CategoryId" class="form-control select-category-option" asp-items="ViewBag.CategoryList">
                        <option value="">-- Select Category --</option>
                    </select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>

                </div>
                <div class="form-group" style="flex:1">
                    <label asp-for="StoreId">Store <span class="span-wraning">*</span></label>
                    <select asp-for="StoreId" class="form-control select-store-option" asp-items="ViewBag.StoreList">
                        <option value="">-- Select Store --</option>
                    </select>
                    <span asp-validation-for="StoreId" class="text-danger"></span>

                </div>
            </div>
            <div style="display:flex; justify-content:flex-start;">
                <div>
                    <button id="submit-product" type="submit" class="btn " style="margin: 0 5px; background-color: #438a7a;color:#ffffff; ">Create Product</button>
                </div>
                <div>
                    <button type="button" class="btn btn-secondary" id="clear-form">Cancel</button>
                </div>
            </div>

        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3 Image-Area" style=" height: auto; border-radius:5px;padding:12px 10px;">
            <div class="image-upload-container">
                <div>
                    <input asp-for="ImagePath" id="file-input" type="file" class="file-input" accept="image/*" />
                    <div class="upload-message">
                        <i class="fas fa-upload"></i> <!-- أيقونة رفع الصورة -->
                        <p style="font-size:19px;">Upload your product image.</p>
                        <p style="font-weight:300"><br>Only PNG, JPG format allowed.<br>500x500 pixels are recommended.</p>
                    </div>
                </div>
            </div>
        </div>


    </section>

</form>



<!-- Include validation scripts -->
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="https://cdn.jsdelivr.net/npm/spin.js@2.3.2/spin.min.js"></script>
    <script>
        

        document.querySelector('.image-upload-container').addEventListener('click', function () {
            document.getElementById('file-input').click();
        });
        // عندما يختار المستخدم صورة جديدة
        document.getElementById('file-input').addEventListener('change', function () {
            var file = this.files[0];

            if (file) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    // عرض الصورة كخلفية
                    document.querySelector('.image-upload-container').style.backgroundImage = 'url(' + e.target.result + ')';
                    //$(".image-upload-container").addClass("image-background");
                    $(".upload-message").addClass("d-none"); // إخفاء نص "Upload your product image"
                };

                reader.readAsDataURL(file);


            }
        });


        $(document).ready(function () {
            $("#submit-product").on('click', function (e) {
                e.preventDefault();
                if (!$('form').valid()) {
                    toastr.info('Please fill in all required fields.', 'Validation Error');
                    return;
                }
                var formData = new FormData();
                formData.append("Name", $("#Name").val());
                formData.append("Code", $("#Code").val());
                formData.append("Description", $("#Description").val());
                formData.append("StockQuantity", $("#StockQuantity").val());
                formData.append("Price", $("#Price").val());
                var categoryId = $("#CategoryId").val();

                // التأكد من أن التصنيف تم اختياره
                if (!categoryId) {
                    toastr.error("Please select a category.", 'info');
                    return;
                }
                formData.append("CategoryId", categoryId);
                var storeId = $("#StoreId").val();

                // التأكد من أن التصنيف تم اختياره
                if (!storeId) {
                    toastr.error("Please select a Store.", 'info');
                    return;
                }
                formData.append("StoreId", storeId);

                var fileInput = document.getElementById('file-input');
                if (fileInput.files.length > 0) {
                    formData.append("imagePath", fileInput.files[0]);
                } else {
                    toastr.error("Please select a Product Image.", 'info');
                    return;
                }
                var spinner = new Spinner().spin();
                document.body.appendChild(spinner.el);
                spinner.spin(document.body);

                $.ajax({
                    url: '@Url.Action("CreateProduct", "Products")',
                    type: "POST",
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (response) {

                        if (response.success == "true") {
                            $("#ProductId").val('');
                            $("#Name").val('');
                            $("#Description").val('');
                            $("#Code").val('');
                            $("#Price").val(0);
                            $("#StockQuantity").val(0);
                            $('.select-category-option').val('').trigger('change');
                            $('.select-store-option').val('').trigger('change');
                            $('.image-upload-container').css('background-image', 'none');
                            $('#file-input').val('');
                            $(".upload-message").removeClass("d-none"); // إخفاء نص "Upload your product image"
                            toastr.success(response.message, 'Sucesss');
                            spinner.stop();
                        } else {

                            toastr.error(response.message, 'Error');
                        }
                    },
                    error: function (xhr, status, error) {
                        toastr.error("Failed to add the product.", 'Error');
                    }
                });
                
            });
        });
        var opts = {
            animation: 'spinner-line-fade-quick', // The CSS animation name for the lines
           
        }
        // Clear Item
        $("#clear-form").on("click", function () {

            $("#ProductId").val('');
            $("#Name").val('');
            $("#Description").val('');
            $("#Code").val('');
            $("#Price").val(0);
            $('#file-input').val('');
            $("#StockQuantity").val(0);
            $('.select-category-option').val('').trigger('change');
            $('.select-store-option').val('').trigger('change');
            $('.image-upload-container').css('background-image', 'none');
            $(".upload-message").removeClass("d-none");
        })

    </script>


    <script>
        // تفعيل Select2 على قائمة التصنيفات
        $(document).ready(function () {
            $('.select-category-option').select2({
                placeholder: "Search for a category", // نص يظهر كعنصر placeholder
                allowClear: true, // للسماح بإزالة الاختيار
                width: '100%', // لضبط العرض
                theme: "classic" // يمكنك استخدام ثيم Select2
            });
            $('.select-store-option').select2({
                placeholder: "Search for a Store", // نص يظهر كعنصر placeholder
                allowClear: true, // للسماح بإزالة الاختيار
                width: '100%', // لضبط العرض
                theme: "classic" // يمكنك استخدام ثيم Select2
            });
        });


    </script>
}

InventoryHubUI/Views/Products/Index.cshtml
@model IEnumerable<InventoryHubUI.DTO.ProductViewModel>

@{
    ViewData["Title"] = "Products";
    var currentPage = ViewData["CurrentPage"] != null ? (int)ViewData["CurrentPage"] : 1;
    var pageSize = ViewData["PageSize"] != null ? (int)ViewData["PageSize"] : 10;
    var totalItems = ViewData["TotalItems"] != null ? (int)ViewData["TotalItems"] : 0;


    var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);
    var hasNextPage = currentPage < totalPages;
    var hasPreviousPage = currentPage > 1;
    int loop = 1;
}
<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }

    /* تنسيق الخلايا في الجدول */
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
    }

    /* تنسيق رأس الجدول */
    th {
        background-color: #f2f2f2;
        text-align: left;
    }

    tr {
        background-color: #ffffff;
    }

        tr:hover {
            background-color: #f9f9f9;
        }

    td {
        text-align: center;
    }

    .create-product {
        position: fixed;
        right: 10px;
    }

    .form-select {
        border-radius: 5px;
        width: 88px;
        height: 34px;
        font-size: 17px;
        text-align: center;
        margin: 0 5px;
    }
    .page-item.active .page-link {
        color: #fff;
        background-color: #438a7a;
        border-color: #438a7a;
    }
    .page-item {
    }
       
</style>
<div style="display:flex;align-items:center;padding:10px 15px;">
    <h2 style="flex:1">Products</h2>
    <a asp-action="CreateProduct" class="btn background-design create-product" >
        <i class="bi bi-plus-circle"></i>
        Create a new product
    </a>
</div>
    <div class="row" style="background-color: #ffffff; margin: 0; padding: 15px 0; border-radius: 5px;">
        <div class="col-md-4">
            <label>
                Show
                <select id="productListTable_length" class="form-select">
                    <option value="10" selected>10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
            </label>
        </div>
        <div class="col-md-6"></div>
        <div class="col-md-2">
            <input type="text" id="searchInput" class="form-control" placeholder="Search...">
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Sr.No</th>
                <th class="d-none">Product ID</th>
                <th>Product Name</th>
                <th>Product Image</th>
                <th>Code</th>
                <th>Price</th>
                <th>Stock Quantity</th>
                <th>@*Category*@</th>
                <th>Store</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model)
            {
                <tr style="line-height:4">
                    <td>@loop</td>
                    <td class="d-none">@product.ProductId</td>
                    <td>
                        <a target="_blank" style="text-decoration:none" asp-action="EditProduct" asp-route-id="@product.ProductId">@product.Name</a>
                    </td>
                    <td>
                        <div style=" width: 60px; height: 60px; overflow: hidden; border-radius: 50%;">
                            <img style="width: 100%; height: 100%;" src="@product.ImagePath" alt="product Image" />

                        </div>
                    </td>
                    <td>@product.Code</td>
                    <td>@product.Price.ToString("C")</td>
                    <td>@product.StockQuantity?.ToString()</td>
                    <td>@*@product.Category.Name*@</td>
                    <td>@product.Store?.StoreName</td>
                </tr>
                loop++;
            }
        </tbody>
    </table>

    <!-- Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item @(hasPreviousPage ? "" : "disabled")">
                <a class="page-link" href="@Url.Action("Index", new { pageNumber = 1, pageSize })" tabindex="-1">First</a>
            </li>
            <li class="page-item @(hasPreviousPage ? "" : "disabled")">
                <a class="page-link" href="@Url.Action("Index", new { pageNumber = currentPage - 1, pageSize })" tabindex="-1">Previous</a>
            </li>

            @for (int i = 1; i <= totalPages; i++)
            {
                <li class="page-item @(i == currentPage ? "active" : "")">
                    <a class="page-link" href="@Url.Action("Index", new { pageNumber = i, pageSize })">@i</a>
                </li>

            }

            <li class="page-item @(hasNextPage ? "" : "disabled")">
                <a class="page-link" href="@Url.Action("Index", new { pageNumber = currentPage + 1, pageSize })">Next</a>
            </li>
            <li class="page-item @(hasNextPage ? "" : "disabled")">
                <a class="page-link" href="@Url.Action("Index", new { pageNumber = totalPages, pageSize })">Last</a>
            </li>
        </ul>
    </nav>


@section Scripts {


    <script>

        $(document).ready(function () {
           
            GetSelectValueFromURL();
            $("#productListTable_length").on("change", function () {
                debugger
                // الحصول على قيمة الحجم الجديد من القائمة المنسدلة
                var pageSize = $(this).val();
                //SetSelectValueToLocalStorage(pageSize);
                

                var fullUrl = window.location.href;

                // إنشاء كائن URL لتحليل الـ URL
                var url = new URL(fullUrl);

                // الحصول على الجزء الأساسي من الـ URL بدون معلمات الاستعلام
                var baseUrl = url.origin + url.pathname;

                // إعادة توجيه المستخدم إلى URL الجديد
                // https://localhost:44375/Products?pageNumber=1&pageSize=20
                window.location.href = baseUrl + "?pageNumber=1&pageSize=" + pageSize;
            });
        });

        
        function GetSelectValueFromURL() {
            
            // Create a new URL object
            const url = new URL(window.location.href);

            const searchParams = url.searchParams; // URLSearchParams object containing query parameters

            // Access individual query parameters
            const pageSize = searchParams.get('pageSize'); // '20'
            if (pageSize)
                $("#productListTable_length").val(pageSize);
            
        }

        // Search Table
            $('#searchInput').on('keyup', function () {
                var value = $(this).val().toLowerCase();
                $('table tbody tr').filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1);
                });
            });
        
    </script>
}